# EXERCISE PROBLEMS

## 1. Compute the Mean and Variance of a Vector

### Problem Statement:
Create a vector (array) of 1xN dimension representing an N-dimensional feature vector of a sample. Write a program to compute the mean and variance of the elements present in the array.

In [18]:
import numpy as np

# Create a vector
x = np.array([3, 7, 2, 9, 5, 4, 6, 8, 2, 10])

# Calculate mean
mean = np.mean(x)

# Calculate variance
variance = np.var(x, ddof=1)

# Print the results
print("Mean:", mean)
print("Variance:", variance)

Mean: 5.6
Variance: 8.266666666666666


## 2. Compute the Covariance between Two Vectors

### Problem Statement:
Create two vectors each of dimension 1xM representing N-dimensional feature vectors of a sample. Write a program to compute the covariance between them.

In [20]:
import numpy as np

# Sample vectors
x = np.array([3, 7, 2, 9, 5, 4, 6, 8, 2, 10])
y = np.array([1, 4, 2, 8, 5, 7, 3, 9, 0, 11])

# Calculate covariance
covariance = np.cov(x, y, ddof=1)[0, 1]

# Print the result
print("Covariance:", covariance)


Covariance: 8.88888888888889


## 3. Compute the Correlation between Two Vectors

### Problem Statement:
Create two vectors each of dimension 1xN. Write a program to compute the correlation between them.

In [29]:
import numpy as np

# Sample vectors
X = np.array([1, 2, 3, 4, 5])
Y = np.array([2, 4, 6, 8, 10])

# Calculate the correlation
correlation = np.corrcoef(X, Y)[0, 1]

# Print the result
print(f"Correlation: {correlation}")


Correlation: 0.9999999999999999


## 4. Compute the Covariance Matrix and Correlation Matrix

### Problem Statement:
Create a matrix of MxN dimension representing the M-dimensional feature vector for N samples (i.e., the (i,j)th entry of the matrix represents the ith feature of the jth sample). Write a program to compute the covariance matrix and correlation matrix.

In [35]:
import numpy as np

# Create a matrix where each column is a feature and each row is a sample
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12],
                   [13, 14, 15]])

# Compute the covariance matrix (with rows as variables)
cov_matrix = np.cov(matrix, rowvar=False)

# Compute the correlation matrix (with rows as variables)
corr_matrix = np.corrcoef(matrix, rowvar=False)

# Print the results
print("Covariance Matrix:")
print(cov_matrix)
print("\nCorrelation Matrix:")
print(corr_matrix)


Covariance Matrix:
[[22.5 22.5 22.5]
 [22.5 22.5 22.5]
 [22.5 22.5 22.5]]

Correlation Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
